language: go

go:
  - "1.10"

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

script:
  - go test -race ./crawler
  - go test -race ./fetcher
  - go test -race ./crawlers-aws/*/
  - cd ./crawlers-aws/ && make