language: go

go:
  - "1.10"

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

script:
  - go test -race ./crawler
  - go test -race ./fetcher
  - go test -race ./crawlers-aws/*/
  - cd ./crawlers-aws/ && make

before_deploy:
  - cd ..
  - npm install -g serverless

deploy:
  # deploy to production if commit is tagged
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh production
  on:
    tags: true