service: radiochecker-crawlers

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  environment:
    STATION_ID_HITRADIO_OE3: "hitradio-oe3"
    STATION_ID_KRONEHIT: "kronehit"
    # set Lambda environment variables based on those of the build server
    RC_API_HOST: ${env:${self:provider.stage}_RC_API_HOST}
    RC_API_KEY: ${env:${self:provider.stage}_RC_API_KEY}
    RC_API_AUTHORIZATION: ${env:${self:provider.stage}_RC_API_AUTHORIZATION}
    TWITTER_CONSUMER_KEY: ${env:${self:provider.stage}_TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_KEY_SECRET: ${env:${self:provider.stage}_TWITTER_CONSUMER_KEY_SECRET}
    TWITTER_OAUTH_ACCESS_TOKEN: ${env:${self:provider.stage}_TWITTER_OAUTH_ACCESS_TOKEN}
    TWITTER_OAUTH_ACCESS_TOKEN_SECRET: ${env:${self:provider.stage}_TWITTER_OAUTH_ACCESS_TOKEN_SECRET}

package:
 exclude:
   - ./**
 include:
   - ../bin/crawlers-aws/**

functions:
  crawler-hitradio-oe3:
    handler: bin/crawlers-aws/hitradio-oe3
    description: Crawler for radio station "Hitradio Ö3"
    memorySize: 512
    timeout: 10
    events:
      - schedule:
          rate: rate(1 hour)
          enabled: true
  crawler-kronehit:
    handler: bin/crawlers-aws/kronehit
    description: Crawler for radio station "Kronehit"
    memorySize: 1024
    timeout: 20
    events:
      - schedule:
          rate: rate(1 hour)
          enabled: true